.TH Utility 1
.SH NAME
Utility \- Categorise files and generate UUIDs
.SH SYNOPSIS
.B ./utility
[\fB\-c\fR \f OUTPUT\fR] |
[\fB\-u\fR \f VERSION | LAST\fR]
.SH DESCRIPTION
.B Utility
can either categorise a file _Directory and it's subdirectories, or generate a UUID version 1 or 4.
.SH OPTIONS
.TP
.BR \-c " " \-\-output =\fI OPTION\fR
Categorises a directory named _Directory.
.RS
    \fBfile, f\fR
    Only save the categorisation to categorise_directory.
    \fBterminal, t\fR
    Save categorisation to categorise_directory.txt, then display result to standard output.
.RE
.TP
.BR \-u " " \-\-version =\fI VERSION " | " LAST\fR
Generate a UUID version 1 or 4. Other versions are not supported.
.RS
    \fB1\fR
    Generate a UUID version 1.
    \fB4\fR
    Generate a UUID version 4.
    \fBlast, l\fR
    Get the last generated UUID.
.RE
.SH EXAMPLES
.TP
.B ./utility -c f
Categorises _Directory and saves the results to a file categorise_directory.txt.
.TP
.B ./utility -c terminal
Categorises _Directory and saves the results to categorise_directory.txt, then concatenates categorise_directory to standard output.
.TP
.B ./utility -u 1
Generates a unique UUID version 1.
.SH SEE ALSO
uuidgen(1), du(1)