.TH UTILITYSCRIPT 1
.SH NAME
UtilityScript.sh \- Categorise files and generate UUIDs
.SH SYNOPSIS
.B ./UtilityScript.sh
[\fB\-c\fR \f OUTPUT\fR] |
[\fB\-u\fR \f VERSION\fR]
.SH DESCRIPTION
.B UtilityScript
can either categorise a file _Directory and it's subdirectories, or generate a UUID version 1 or 4.
.SH OPTIONS
.TP
.BR \-c " " \-\-output =\fI OPTION\fR
Categorises a directory named _Directory.
.RS
    \fBfile, f\fR
    Only save the categorisation to categorise_directory.
    \fBterminal, t\fR
    Save categorisation to categorise_directory.txt, then display result to standard output.
.RE
.TP
.BR \-u " " \-\-version =\fI VERSION\fR
Generate a UUID version 1 or 4. Other versions are not supported.
.SH EXAMPLES
.TP
.B ./UtilityScript.sh -c f
Categorises _Directory and saves the results to a file categorise_directory.txt.
.TP
.B ./UtilityScript.sh -c terminal
Categorises _Directory and saves the results to categorise_directory.txt, then concatenates categorise_directory to standard output.
.TP
.B ./UtilityScript.sh -u 1
Generates a unique UUID version 1.
.SH SEE ALSO
uuidgen(1), du(1)